# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Instect, Inc.
"""Pydantic v2 emitter — wraps `datamodel-code-generator`.

For each input schema file we produce one Python module under the output dir,
named after the schema's filename with `.` and `-` replaced by `_`. An
`__init__.py` is rewritten on every run with `from .<module> import *` lines
so downstream code can `from instect_core._generated import EvalSpec`.

We strip toolchain-volatile lines (`# generated by datamodel-codegen ...`,
`#   timestamp: ...`) from each emitted module so the output is reproducible.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

GENERATED_HEADER = (
    "# SPDX-License-Identifier: Apache-2.0\n"
    "# SPDX-FileCopyrightText: 2026 Instect, Inc.\n"
    "# @generated — DO NOT EDIT. Regenerate via `just codegen`.\n"
)

_VOLATILE_LINE_RE = re.compile(
    r"^# +(generated by datamodel-codegen|timestamp:|filename:).*$",
    re.MULTILINE,
)


def _module_name(rel_path: Path) -> str:
    """Turn `insect.eval.v1/common.json` → `insect_eval_v1__common`.

    `rel_path` must already be relative to `schemas_root`.
    """
    stripped = rel_path.with_suffix("")  # drop .json
    parts = [p.replace(".", "_").replace("-", "_") for p in stripped.parts]
    return "__".join(parts)


def _scrub(text: str) -> str:
    """Remove toolchain-volatile lines so output is reproducible."""
    return _VOLATILE_LINE_RE.sub("", text).lstrip("\n")


def _emit_empty_init(out_dir: Path) -> None:
    init_py = out_dir / "__init__.py"
    init_py.write_text(GENERATED_HEADER + '"""Generated Pydantic models. Empty until schemas land."""\n')


def _emit_one(schema_path: Path, schemas_root: Path, out_dir: Path) -> str | None:
    """Emit a single schema → module. Returns module name on success, else None."""
    try:
        rel = schema_path.relative_to(schemas_root)
    except ValueError:
        rel = Path(schema_path.name)
    mod = _module_name(rel)
    target = out_dir / f"{mod}.py"

    cmd = [
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input",
        str(schema_path),
        "--input-file-type",
        "jsonschema",
        "--output",
        str(target),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.12",
        "--use-standard-collections",
        "--use-union-operator",
        "--disable-timestamp",
        "--use-schema-description",
        "--use-field-description",
        "--snake-case-field",
    ]
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
    except FileNotFoundError:
        print(
            "[codegen-python] `datamodel-code-generator` not installed; "
            "install via `uv pip install -r tools/codegen/requirements.txt`",
            file=sys.stderr,
        )
        return None
    except subprocess.CalledProcessError as exc:
        print(
            f"[codegen-python] datamodel-codegen failed for {schema_path}:\n{exc.stderr}",
            file=sys.stderr,
        )
        return None

    if target.exists():
        body = target.read_text()
        target.write_text(GENERATED_HEADER + _scrub(body))
    return mod


def generate(schemas: list[Path], schemas_root: Path, out_dir: Path) -> None:
    """Generate Pydantic modules into `out_dir`. Robust to empty `schemas` list."""
    import shutil

    # Clean stale outputs but keep the dir.
    for child in out_dir.iterdir() if out_dir.exists() else []:
        if child.is_file():
            child.unlink()
        elif child.is_dir():
            shutil.rmtree(child)

    if not schemas:
        _emit_empty_init(out_dir)
        return

    modules: list[str] = []
    for s in schemas:
        m = _emit_one(s, schemas_root, out_dir)
        if m is not None:
            modules.append(m)

    init_lines = [
        GENERATED_HEADER,
        '"""Generated Pydantic v2 models for the `insect.eval.v1` schema family."""\n',
        "from __future__ import annotations\n\n",
    ]
    for m in sorted(modules):
        init_lines.append(f"from . import {m} as {m}  # noqa: F401\n")
    (out_dir / "__init__.py").write_text("".join(init_lines))


def _self_metadata() -> dict[str, str]:
    """Used by ad-hoc CI logs; safe to ignore."""
    return {"emitter": "codegen_python", "header": GENERATED_HEADER.strip().splitlines()[-1]}


if __name__ == "__main__":  # pragma: no cover — module is normally imported
    print(json.dumps(_self_metadata()))
